apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-k8s-cicd
spec:
  template:
    metadata:
      labels:
        app: jenkins-k8s-cicd
    spec:
      containers:
      - image: uhub.service.ucloud.cn/jenkins_k8s_cicd/jenkins_k8s_cicd:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-k8s-cicd
        env:
        - name: branch
          value: <BRANCH_NAME>
